name: deploy-to-aws
description: Deploys the application to AWS Elastic Beanstalk
inputs:
  dockerhub_username:
    description: Username to DockerHub
    required: true
  dockerhub_password:
    description: Password to DockerHub
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    - name: Build Angular app and push
      uses: docker/build-push-action@v2
      with:
        context: ../../
        file: docker/nginx/Dockerfile
        push: true
        tags: processpuzzle-testbed/processpuzzle-testbed:latest

    - name: Build json-server and push
      uses: docker/build-push-action@v2
      with:
        context: ../../
        file: docker/json-server/Dockerfile
        push: true
        tags: processpuzzle-testbed/json-server:latest
