name: release-java
description: Release Java artifacts to Maven Central
inputs:
  base_dir:
    description: Base director of the source code
    required: true
  nx_project:
    description: Name of the Nx project
    required: true
  github_token:
    description: Token to get access to Github
    required: true
  sonar_token:
    description: Token to get access to SonarCloud
    required: true
  gpg_private_key:
    description: GPG private key for signing artifacts
    required: true
  gpg_passphrase:
    description: GPG passphrase for signing artifacts
    required: true
  central_token_username:
    description: Username for Maven Central token
    required: true
  central_token_password:
    description: Password for Maven Central token
    required: true
  cicd_stage:
    description: Actual stage in the CI/CD pipeline
    required: false
    default: 'ci'
  node-version:
    description: NodeJS version to use
    required: false
    default: '24.x'
  java-version:
    description: Java version to use
    required: false
    default: '25.x'
runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org
        cache: 'npm'
        cache-dependency-path: |
          package.json
          package-lock.json

    - name: Setup Java
      uses: actions/setup-java@v4.8.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Config Git
      shell: bash
      run: |
        git config --global user.email "zsolt.zsuffa@gmail.com"
        git config --global user.name "Zsolt Zsuffa"

    - name: Import GPG key
      shell: bash
      run: |
        echo "${{ inputs.gpg_private_key }}" | gpg --batch --import
        gpg --list-secret-keys

    - name: Read POM version
      id: version
      shell: bash
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      working-directory: ${{inputs.base_dir}}

    - name: Publish to Maven Central
      run: mvn --batch-mode --settings ./settings.xml deploy -Prelease
      working-directory: ${{ inputs.base_dir }}
      env:
        MAVEN_USERNAME: ${{ inputs.central_token_username }}
        MAVEN_PASSWORD: ${{ inputs.central_token_password }}
        GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
      shell: bash

    - name: Create GitHub Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      with:
        title: "@processpuzzle/${{inputs.nx_project}}/${{steps.version.outputs.VERSION}}"
        tag: "${{inputs.nx_project}}@${{steps.version.outputs.VERSION}}"
