networks:
  processpuzzle:
    driver: bridge

services:
  processpuzzle-testbed:
    depends_on:
      - json-server
      - firebase
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
      args:
        CICD_STAGE: ci
    image: processpuzzle-testbed
    container_name: processpuzzle-testbed
    ports:
      - "8080:80"
    tty: true
    networks:
      - processpuzzle
  json-server:
    build:
      context: ../
      dockerfile: docker/json-server/Dockerfile
    image: json-server
    container_name: json-server
    ports:
      - "3000:3000"
    tty: true
    networks:
      - processpuzzle
  firebase:
    image: firebase
    build:
      context: ../
      dockerfile: docker/firebase/Dockerfile
      args:
        - FIREBASE_VERSION=13.33.0
    stop_grace_period: 1m
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"
      FIRESTORE_EMULATOR_HOST: "localhost:9090"
      PUBSUB_EMULATOR_HOST: "localhost:8085"
      FUNCTIONS_EMULATOR_HOST: "localhost:5001"
      FIREBASE_PROJECT: "processpuzzle-testbed-stage"
      GCLOUD_PROJECT: "processpuzzle-testbed-stage"
      FORCE_COLOR: 'true'
      DATA_DIRECTORY: "data"
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "4000:4001" # ui
      - "4400:4401" # hub
      - "4600:4601" # logging
      - "5001:5002" # functions
      - "9090:8080" # firestore
      - "8085:8086" # pubsub
      - "9099:9100" # auth
      - "9199:9200" # Storage
    volumes:
      - ./firebase:/srv/firebase:rw
      - ./cache:/root/.cache/:rw
      - ~/.config/:/root/.config
      - ./firebase/data:/srv/firebase/data:rw
