networks:
  processpuzzle:
    driver: bridge

services:
  processpuzzle-testbed:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    image: processpuzzle-testbed
    container_name: processpuzzle-testbed
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    tty: true
    networks:
      - processpuzzle
  json-server:
    build:
      context: ../
      dockerfile: docker/json-server/Dockerfile
    image: json-server
    container_name: json-server
    ports:
      - "4000:3000"
    tty: true
    networks:
      - processpuzzle
