networks:
  processpuzzle:
    driver: bridge

services:
  processpuzzle-testbed:
    depends_on:
      json-server:
        condition: service_healthy
      firebase:
        condition: service_healthy
    build:
      context: ../
      dockerfile: docker/testbed/Dockerfile
      args:
        CICD_STAGE: ci
    image: zsuffazs/processpuzzle-testbed:latest
    container_name: processpuzzle-testbed
    environment:
      PIPELINE_STAGE: "CI"
      FIREBASE_API_KEY: $FIREBASE_API_KEY
    ports:
      - "9090:80"
    tty: true
    networks:
      - processpuzzle
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9090/home" ]
  json-server:
    build:
      context: ../
      dockerfile: docker/json-server/Dockerfile
    image: zsuffa/json-server:latest
    container_name: json-server
    ports:
      - "3000:3000"
    tty: true
    networks:
      - processpuzzle
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:3000/test-entity" ]
  firebase:
    image: zsuffazs/firebase-emulator:latest
    container_name: firebase-emulator
    build:
      context: ../
      dockerfile: docker/firebase/Dockerfile
      args:
        - FIREBASE_VERSION=13.33.0
    stop_grace_period: 1m
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"
      FIRESTORE_EMULATOR_HOST: "localhost:8080"
      PUBSUB_EMULATOR_HOST: "localhost:8085"
      FUNCTIONS_EMULATOR_HOST: "localhost:5001"
      FIREBASE_PROJECT: "processpuzzle-testbed-stage"
      GCLOUD_PROJECT: "processpuzzle-testbed-stage"
      FORCE_COLOR: 'true'
      DATA_DIRECTORY: "data"
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "4000:4001" # ui
      - "4400:4401" # hub
      - "4600:4601" # logging
      - "5001:5002" # functions
      - "8080:8081" # firestore
      - "8085:8086" # pubsub
      - "9000:9001" # database
      - "9099:9100" # auth
      - "9199:9200" # Storage
      - "6000:6001" # Hosting
    volumes:
      - ./firebase:/srv/firebase:rw
      - ~/.config/:/root/.config
      - ./firebase/data:/srv/firebase/data:rw
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]
