version: '3.8'
networks:
  qk-ng:
    driver: bridge

services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    image: qk-ng_nginx
    container_name: qk-ng_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    tty: true
    networks:
      - qk-ng
  json-server:
    build:
      context: ../
      dockerfile: docker/json-server/Dockerfile
    image: qk-ng_json-server
    container_name: qk-ng_json-server
    ports:
      - "4000:3000"
    tty: true
    networks:
      - qk-ng
