networks:
  processpuzzle:
    driver: bridge

services:
  processpuzzle-testbed:
    depends_on:
      - json-server
    image: zsuffazs/processpuzzle-testbed:latest
    container_name: processpuzzle-testbed
    ports:
      - "80:80"
    networks:
      - processpuzzle
  json-server:
    image: zsuffazs/json-server:latest
    container_name: json-server
    ports:
      - "3000:3000"
    networks:
      - processpuzzle
