name: lint-test-build
description: Lint test and build the application
inputs:
  github_token:
    description: Token to get access to Github
    required: true
  sonar_token:
    description: Token to get access to SonarCloud
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      shell: bash
    - name: Lint libs and apps
      run: npm run lint-all-ci
      shell: bash
    - name: Test libs and apps
      run: npm run test-all-ci
      shell: bash
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
    - name: Build libs and apps
      run: npm run build-all-ci --if-present
      shell: bash
