name: lint-test-build
description: Lint test and build the application
inputs:
  base_dir:
    description: Base director of the source code
    required: true
  nx_project:
    description: Name of the Nx project
    required: true
  github_token:
    description: Token to get access to Github
    required: true
  sonar_token:
    description: Token to get access to SonarCloud
    required: true
  firebase_token:
    description: Firebase key
    required: true
  cicd_stage:
    description: Actual stage in the CI/CD pipeline
    required: true
    default: 'ci'
runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      shell: bash
    - name: Lint libs and apps
      run: npm run lint-${{inputs.nx_project}}
      shell: bash
    - name: Test libs and apps
      run: npm run test-${{inputs.nx_project}}
      shell: bash
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      with:
        projectBaseDir: ${{inputs.base_dir}}
    - name: Generate environment file
      run: npm run config-env-${{inputs.nx_project}} -- --environment=${{inputs.cicd_stage}}
      env:
        FIREBASE_API_KEY: ${{inputs.firebase_token}}
        PIPELINE_STAGE: ${{inputs.cicd_stage}}
      shell: bash
    - name: Build libs and apps
      run: npm run build-${{inputs.nx_project}} --if-present
      shell: bash

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-report-${{ github.sha }}
        path: libs/${{inputs.nx_project}}/reports/coverage/lcov-report
        retention-days: 30
