name: lint-test-build
description: Lint test and build the application
inputs:
  base_dir:
    description: Base director of the source code
    required: true
  nx_project:
    description: Name of the Nx project
    required: true
  github_token:
    description: Token to get access to Github
    required: true
  sonar_token:
    description: Token to get access to SonarCloud
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      shell: bash
    - name: Lint libs and apps
      run: npm run lint-${{inputs.nx_project}}
      shell: bash
    - name: Test libs and apps
      run: npm run test-${{inputs.nx_project}}
      shell: bash
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      with:
        projectBaseDir: ${{inputs.baseDir}}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
    - name: Build libs and apps
      run: npm run build-${{inputs.nx_project}} --if-present
      shell: bash
