// @ts-expect-error I don't understand the error, but it works
const { writeFile, existsSync, mkdirSync } = require('node:fs');
// Removed yargs (ESM-only) to avoid ERR_REQUIRE_ESM when running via ts-node in CJS mode
require('dotenv').config();

function getCliArg(name: string): string | undefined {
  const prefix = `--${name}`;
  const argv = process.argv;
  const idx = argv.findIndex((a) => a === prefix || a.startsWith(prefix + '='));
  if (idx === -1) return undefined;
  const current = argv[idx];
  if (current.includes('=')) return current.split('=')[1];
  return argv[idx + 1];
}

// @ts-expect-error I don't understand the error, but it works
const environment = getCliArg('environment');

function writeFileUsingFS(targetPath: string, environmentFileContent: string) {
  writeFile(targetPath, environmentFileContent, function (err: string) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`write ${environmentFileContent} to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
// @ts-expect-error I don't understand the error, but it works
const envDirectory = 'apps/processpuzzle-testbed/src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts`, `environment.test.ts` and `environment.ts` file if it does not exist
writeFileUsingFS(`${envDirectory}/environment.dev.ts`, '');
writeFileUsingFS(`${envDirectory}/environment.ci.ts`, '');
writeFileUsingFS(`${envDirectory}/environment.prod.ts`, '');
writeFileUsingFS(`${envDirectory}/environment.stage.ts`, '');
writeFileUsingFS(`${envDirectory}/environment.ts`, '');

// choose the correct targetPath based on the environment chosen
// @ts-expect-error I don't understand the error, but it works
let targetPath: string;

switch (environment) {
  case 'dev':
    targetPath = `${envDirectory}/environment.dev.ts`;
    break;
  case 'ci':
    targetPath = `${envDirectory}/environment.ci.ts`;
    break;
  case 'stage':
    targetPath = `${envDirectory}/environment.stage.ts`;
    break;
  case 'prod':
    targetPath = `${envDirectory}/environment.prod.ts`;
    break;
  default:
    targetPath = `${envDirectory}/environment.ts`;
    break;
}

//actual content to be compiled dynamically and pasted into respective environment files
// @ts-expect-error I don't understand the error, but it works
const environmentFileContent = `

  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  import { EnvironmentVariables } from './environment-variables';

  export const environment: EnvironmentVariables = {
    FIREBASE_API_KEY: '${process.env['FIREBASE_API_KEY']}',
    PIPELINE_STAGE: '${process.env['PIPELINE_STAGE']}'
  };

`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file/* eslint:enable */
writeFileUsingFS(`${envDirectory}/environment.ts`, environmentFileContent);
