name: e2e-tests
description: End to End playwright tests
inputs:
  target_environment:
    description: Target environment.
    required: true
    default: ci
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      shell: bash

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash

    - name: Run Playwright tests
      run: npm run e2e-test-processpuzzle-testbed
      shell: bash
      env:
        ENVIRONMENT: ${{inputs.target_url}}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: dist/.playwright/apps/processpuzzle-testbed-e2e
        retention-days: 30
