-- definition module ----------------------------------------------------------

create table base_entity_definition (
    id                 uuid primary key,
    code               varchar(255) not null,
    name               varchar(255) not null,
    description        text,
    version            bigint not null default 0,
    status             varchar(32)  not null default 'DRAFT',
    component_parents  jsonb        not null default '[]'::jsonb,
    is_embedded        boolean      not null default false,
    organization_id    uuid,
    created_at         timestamptz  not null default now(),
    created_by         varchar(255),
    updated_at         timestamptz  not null default now(),
    updated_by         varchar(255),
    constraint uq_base_entity_definition_code unique (code)
);

create index idx_base_entity_definition_component_parents
    on base_entity_definition using gin (component_parents jsonb_path_ops);

create table base_entity_attribute (
    id                    uuid primary key,
    entity_definition_id  uuid not null references base_entity_definition (id) on delete cascade,
    code                  varchar(255) not null,
    name                  varchar(255) not null,
    display_order         integer not null default 0,
    value_kind            varchar(32)  not null,
    form_control_type     varchar(32)  not null,
    is_multi_valued       boolean not null default false,
    required              boolean not null default false,
    indexed               boolean not null default false,
    default_value         jsonb,
    enum_values           jsonb,
    linked_entity_type    varchar(255),
    is_link_to_details    boolean not null default false,
    validation_rules      jsonb,
    constraint uq_base_entity_attribute_def_code unique (entity_definition_id, code)
);

-- instances module -------------------------------------------------------------

create table entity_object (
    id                     uuid primary key,
    entity_definition_code varchar(255) not null
        references base_entity_definition (code),
    version                bigint not null default 0,
    payload                jsonb  not null default '{}'::jsonb,
    created_at             timestamptz not null default now(),
    created_by             varchar(255),
    updated_at             timestamptz not null default now(),
    updated_by             varchar(255)
);

create index idx_entity_object_definition_code on entity_object (entity_definition_code);

-- General-purpose containment/equality index. Helps RSQL ==, !=, =in= reasonably
-- well; does NOT help =gt=/=lt=/=between= range queries — see
-- BaseEntityAttribute.indexed and the instances module's RSQL adapter for those.
create index idx_entity_object_payload on entity_object using gin (payload jsonb_path_ops);

-- Example of a per-attribute expression index for a top-level, non-array,
-- numeric attribute marked indexed=true. Generate one of these per opted-in
-- attribute (via a follow-up migration, or an admin action that emits DDL) —
-- NOT auto-generated by this migration.
--
-- create index idx_entity_object_payload_age
--     on entity_object (((payload ->> 'age')::numeric));
