# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - run: echo "selected runner = ${{ runner.name }}"
      - id: lint-test-build
        name: Lint test and build the application
        uses: ../actions/lint-test-build.yml
      - id: deploy-to-aws
        name: Deploy distribution to AWS
        uses: ../actions/deploy-to-aws.yml
        with:
          distribution_source_path: ./dist/apps/processpuzzle-testbed/browser
