# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build, Lint and Test

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - run: echo "selected runner = ${{ runner.name }}"
      - name: Checkout source code
        uses: actions/checkout@v4
      - run: echo "selected runner = ${{ runner.name }}"

      - id: lint-test-build
        name: Lint test and build the application
        uses: ./.github/actions/lint-test-build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - id: docker-compose
        name: run-docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker/docker-compose-ci.yaml'

      - id: e2e-test
        name: run-e2e-tests
        uses: ./.github/actions/e2e-test
        with:
          target_environment: 'ci'
