name: Build-Testbed
on:
  push:
    branches:
      - "feature/*"
    paths:
      - 'apps/processpuzzle-testbed/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "develop" ]
    paths:
      - 'apps/processpuzzle-testbed/**'
  workflow_run:
    workflows: [ "Build-Util", "Build-Base-Entity" ]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    outputs:
      RUNNER: ${{ runner.name }}
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - id: lint-test-build
        name: Lint test and build the application
        uses: ./.github/actions/lint-test-build
        with:
          base_dir: 'apps/processpuzzle-testbed'
          nx_project: testbed
          github_token: ${{secrets.GITHUB_TOKEN}}
          sonar_token: ${{secrets.SONAR_TOKEN}}

      - id: docker-compose
        name: run-docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker/docker-compose-ci.yaml'

      - id: e2e-test
        name: run-e2e-tests
        uses: ./.github/actions/e2e-test
        with:
          target_environment: 'ci'
