name: Deploy-Testbed
on:
  push:
    branches:
      - "develop"
    paths:
      - 'apps/processpuzzle-testbed/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - id: lint-test-build
        name: Lint test and build the application
        uses: ./.github/actions/lint-test-build
        with:
          base_dir: 'apps/processpuzzle-testbed'
          nx_project: testbed
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - id: build-image
        name: Build and publish Docker images
        uses: ./.github/actions/build-image
        with:
          cicd_stage: 'stage'
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: deploy-to-firebase
        name: Deploy to Firebase host
        uses: ./.github/actions/deploy-to-firebase
        with:
          firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          project_id: processpuzzle-testbed-stage
          channel_id: 'live'
          project_root: .

      - id: integration-test
        name: run-integration-tests
        uses: ./.github/actions/e2e-test
        with:
          target_environment: 'stage'
