name: Publish to NPM
on:
  push:
    branches: [ "release/*" ]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci
      - name: Build libs
        run: npm run build-util-ci --if-present
      - name: Publish package on NPM 📦
        run: nx release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
