name: Publish to NPM

# Rules that triggers the workflows
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Additional steps to get a version and package name from a tag
      # it will not be used in this example, but might be useful for some
      # customization (like additional release of the package, or some external notifications)
      - name: Get Version
        run: |
          TAG_NAME=${{github.event.release.tag_name}}
          echo "PACKAGE_NAME=$(echo $TAG_NAME | cut -d "@" -f 1)" >> $GITHUB_ENV
          echo "APP_VERSION=$(echo $TAG_NAME | cut -d "@" -f 2)" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - id: lint-test-build
        name: Lint test and build the application
        uses: ./.github/actions/lint-test-build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Publish packages
        run: |
          git config --global user.email "zsolt.zsuffa@gmail.com"
          git config --global user.name "Zsolt Zsuffa"
          npx nx release publish --no-cloud
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
