name: Publish to NPM
on:
  push:
    branches: [ "release/*" ]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci
      - name: Install Nx CLI
        run: npm i -g @nrwl/cli
      - name: Set git author
        run: git config --global user.email "zsolt.zsuffa@gmail.com" && git config --global user.name "Zsolt Zsuffa"
      - name: Publish package on NPM 📦
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
