name: Release-Testbed
on:
  push:
    branches:
      - "release/testbed/*"
    paths:
      - 'apps/processpuzzle-testbed/**'
permissions:
  id-token: write
  contents: write
  pull-requests: write
  repository-projects: write
jobs:
  release-to-firebase-prod:
    environment: PROD
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: package-version
        name: Get Version from package.json
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/processpuzzle-testbed

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Sets the base and head SHAs for the nx affected commands in CI
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - id: lint-test-build
        name: Lint test and build the application
        uses: ./.github/actions/lint-test-build
        with:
          base_dir: 'apps/processpuzzle-testbed'
          nx_project: testbed
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          cicd_stage: 'prod'

      - id: build-images
        name: Build and publish Docker images
        uses: ./.github/actions/build-image
        with:
          cicd_stage: 'prod'
          app_version: '${{ steps.package-version.outputs.current-version }}'
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: deploy-to-firebase
        name: Deploy to Firebase host
        uses: ./.github/actions/deploy-to-firebase
        with:
          firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          project_id: processpuzzle-testbed
          channel_id: 'live'
          project_root: .

      - id: integration-test
        name: run-integration-tests
        uses: ./.github/actions/e2e-test
        with:
          target_environment: 'prod'

      - name: Config Git
        shell: bash
        run: |
          git config --global user.email "zsolt.zsuffa@gmail.com"
          git config --global user.name "Zsolt Zsuffa"

      - name: Copy package.json
        shell: bash
        run: |
          cp -R apps/processpuzzle-testbed/package.json dist/apps/processpuzzle-testbed
          cp -R apps/processpuzzle-testbed/README.md dist/apps/processpuzzle-testbed
          rm dist/apps/processpuzzle-testbed/browser/environments/environment.ts

      - name: Publish packages
        shell: bash
        run: npx nx release publish --projects=processpuzzle-testbed --access public --no-cloud
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "@processpuzzle/testbed/${{steps.package-version.outputs.current-version}}"
          tag: "testbed@${{steps.package-version.outputs.current-version}}"
