name: Release-Auth
on:
  push:
    branches:
      - "release/auth/*"
    paths:
      - 'libs/auth/**'
permissions:
  id-token: write
  contents: write
  pull-requests: write
  repository-projects: write
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: package-version
        name: Get Version from package.json
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: 'libs/auth'

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Sets the base and head SHAs for the nx affected commands in CI
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - id: lint-test-build
        name: Lint test and build the application
        uses: ./.github/actions/lint-test-build
        with:
          base_dir: "libs/auth"
          nx_project: 'auth'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Config Git
        shell: bash
        run: |
          git config --global user.email "zsolt.zsuffa@gmail.com"
          git config --global user.name "Zsolt Zsuffa"

      - name: Publish packages
        shell: bash
        run: npx nx release publish --projects=auth --access public --no-cloud
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "@processpuzzle/auth/${{steps.package-version.outputs.current-version}}"
          tag: "auth@${{steps.package-version.outputs.current-version}}"
